### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by d3mystified** [westsurname/scripts#2]
```
[2024-04-10 04:24:09.432253] radarr/sonarr: sonarr
[2024-04-10 04:24:09.432282] getFiles
[2024-04-10 04:24:09.432366] filename: Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb[rartv].magnet
[2024-04-10 04:24:09.433129] [Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb[rartv]] hash: 4D134D96ECFE0EE81E744B3F277E3202F18F6703
[2024-04-10 04:24:10.012965] [Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb[rartv]] instantAvailabilities: {'4d134d96ecfe0ee81e744b3f277e3202f18f6703': {'rd': []}}
[2024-04-10 04:24:10.015436] [Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb[rartv]] instantAvailability: False
[2024-04-10 04:24:10.015524] [Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb[rartv]] Failing
[2024-04-10 04:24:10.032244] [Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb[rartv]] Error processing Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb[rartv]
[2024-04-10 04:24:10.032331] [Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb[rartv]] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/blackhole.py", line 310, in processFile
    if torrent.submitTorrent():
  File "/app/blackhole.py", line 88, in submitTorrent
    self.fail(self)
  File "/app/blackhole.py", line 293, in fail
    history = arr.getHistory(blackhole['historyPageSize'])['records']
  File "/app/shared/arr.py", line 160, in getHistory
    history = historyRequest.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Magnet:

```
magnet:?xt=urn:btih:4D134D96ECFE0EE81E744B3F277E3202F18F6703&dn=Bad.Sisters.S01.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-NTb%5brartv%5d&tr=http%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.auctor.tv%3a6969%2fannounce&tr=udp%3a%2f%2fopentracker.i2p.rocks%3a6969%2fannounce&tr=https%3a%2f%2fopentracker.i2p.rocks%3a443%2fannounce&tr=udp%3a%2f%2fopen.demonii.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a6969%2fannounce&tr=http%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2fopen.stealth.si%3a80%2fannounce&tr=udp%3a%2f%2ftracker.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2ftracker.moeking.me%3a6969%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce&tr=udp%3a%2f%2fuploads.gamecoast.net%3a6969%2fannounce&tr=udp%3a%2f%2ftracker1.bt.moack.co.kr%3a80%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.theoks.net%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.skyts.net%3a6969%2fannounce&tr=udp%3a%2f%2ftracker-udp.gbitt.info%3a80
```

**Comment by westsurname** [comment]
Is this still an issue? Does this happen every file?

**Comment by westsurname** [comment]
Closed due to inactivity. Feel free to reopen if still an issue.

**Comment by wokkieman** [comment]
> Actually I just tried 3 more and they all fail. Nothing about my setup has changed and the last successful import was yesterday from the arr's. So no clue what's going on. I can `curl` my arr's just fine from the docker network that blackhole is a part of.

had the same issue, check your env file

RADARR_HOST=http://xxx:7878  <=== without / at the end
